import Vue from "vue";
import Vuex from "vuex";
import axios from 'axios'
Vue.use(Vuex);
Vue.use(axios)

export default new Vuex.Store({
    state: {
        isLogin: true,
        teams: [{
                id: 1,
                name: "Frozen Yogurt",
                manager: {
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                members: [{
                        id: 0,
                        name: "Liam	Olivia",
                        salary: 15900,
                        status: "worker",
                        period: 1,
                        contact: "sarasgmail.com",
                        pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                    },
                    {
                        id: 1,
                        name: "Noah	Emma",
                        salary: 23700,
                        status: "worker",
                        period: 13,
                        contact: "gmail.com",
                        pic: "https://cdn.psychologytoday.com/sites/default/files/styles/article-inline-half-caption/public/field_blog_entry_images/2018-09/shutterstock_648907024.jpg?itok=0hb44OrI",
                    },
                    {
                        id: 2,
                        name: "Oliver	Ava",
                        salary: 26200,
                        status: "worker",
                        period: 2,
                        contact: "gmail.com",
                        pic: "https://qodebrisbane.com/wp-content/uploads/2019/07/This-is-not-a-person-2-1.jpeg",
                    },
                    {
                        id: 3,
                        name: "William	Sophia",
                        salary: 30500,
                        status: "worker",
                        period: 1,
                        contact: "gmail.com",
                        pic: "https://play-images-prod-cms.tech.tvnz.co.nz/api/v1/web/image/content/dam/images/entertainment/shows/p/person-of-interest/personofinterest_coverimg.png.2017-03-08T11:21:33+13:00.jpg?width=960&height=540",
                    },
                    {
                        id: 4,
                        name: "Elijah	Isabella",
                        salary: 35600,
                        status: "worker",
                        period: 5,
                        contact: "gmail.com",
                        pic: "https://cdn.now.howstuffworks.com/media-content/0b7f4e9b-f59c-4024-9f06-b3dc12850ab7-1920-1080.jpg",
                    },
                    {
                        id: 5,
                        name: "James	Charlotte",
                        salary: 37500,
                        status: "worker",
                        period: 3,
                        contact: "gmail.com",
                        pic: "https://thumbor.forbes.com/thumbor/fit-in/1200x0/filters:format(jpg)/https://specials-images.forbesimg.com/imageserve/5f469ea85cc82fc8d6083f05/0x0.jpg",
                    },
                    {
                        id: 6,
                        name: "Benjamin	Amelia",
                        salary: 39200,
                        status: "worker",
                        period: 1,
                        contact: "gmail.com",
                        pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNsO8UKeJSffZI-UxtGBNbV_VHSel-RHHtog&usqp=CAU",
                    },
                    {
                        id: 7,
                        name: "Lucas	Mia",
                        salary: 40800,
                        status: "intern student",
                        period: 1,
                        contact: "gmail.com",
                        pic: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8cGVyc29ufGVufDB8fDB8&ixlib=rb-1.2.1&w=1000&q=80",
                    },
                    {
                        id: 8,
                        name: "Mason	Harper",
                        salary: 45200,
                        status: "intern student",
                        period: 1,
                        contact: "gmail.com",
                        pic: "http://www.scottcochrane.com/wp-content/uploads/2018/05/One-Person-2.jpg",
                    },
                    {
                        id: 9,
                        name: "Ethan	Evelyn",
                        salary: 51800,
                        status: "intern student",
                        period: 1,
                        contact: "gmail.com",
                        pic: "https://www.guinnessworldrecords.com/Images/Greta-Thunberg-youngest-time-person-of-the-yearthumbnail_tcm25-603423.jpg",
                    },
                ],
                progress: 20,
                img: "",
            },
            {
                id: 2,
                name: "Ice cream sandwich",
                manager: {
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                members: [{
                        id: 0,
                        name: "Liam	Olivia",
                        salary: 15900,
                        status: "worker",
                        period: 1,
                        contact: "sarasgmail.com",
                        pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                    },
                    {
                        id: 1,
                        name: "Noah	Emma",
                        salary: 23700,
                        status: "worker",
                        period: 13,
                        contact: "gmail.com",
                        pic: "https://cdn.psychologytoday.com/sites/default/files/styles/article-inline-half-caption/public/field_blog_entry_images/2018-09/shutterstock_648907024.jpg?itok=0hb44OrI",
                    },
                    {
                        id: 2,
                        name: "Oliver	Ava",
                        salary: 26200,
                        status: "worker",
                        period: 2,
                        contact: "gmail.com",
                        pic: "https://qodebrisbane.com/wp-content/uploads/2019/07/This-is-not-a-person-2-1.jpeg",
                    },
                ],
                progress: 90,
                img: "",
            },
            {
                id: 3,
                name: "Eclair",
                manager: {
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                members: [],
                progress: 30,
                img: "",
            },
            {
                id: 4,
                name: "Cupcake",
                manager: {
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                members: [],
                progress: 100,
                img: "",
            },
            {
                id: 5,
                name: "Gingerbread",
                members: [],
                progress: 81,
                img: "",
            },
            {
                id: 6,
                name: "Jelly bean",
                manager: {
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                members: [],
                progress: 40,
                img: "",
            },
            {
                id: 7,
                name: "Lollipop",
                manager: {
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                members: [],
                progress: 99,
                img: "",
            },
            {
                id: 8,
                name: "Honeycomb",
                manager: {
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                members: [],
                progress: 12,
                img: "",
            },
            {
                id: 9,
                name: "Donut",
                manager: {
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                members: [],
                progress: 60,
                img: "",
            },
            {
                id: 10,
                name: "KitKat",
                manager: {
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                members: [],
                progress: 50,
                img: "",
            },
        ],
        events: [{
                name: "event1",
                startDate: "03/18/2021",
                deadLine: "04/8/2021",
                Team: "Apple",
                finish: true,
            },
            {
                name: "event2",
                startDate: "03/18/2021",
                deadLine: "04/9/2021",
                Team: "Apple",
                finish: false,
            },
            {
                name: "event3",
                startDate: "03/18/2021",
                deadLine: "04/10/2021",
                Team: "Apple",
                finish: true,
            },
            {
                name: "event4",
                startDate: "03/18/2021",
                deadLine: "04/20/2021",
                Team: "Apple",
                finish: true,
            },
            {
                name: "event5",
                startDate: "03/18/2021",
                deadLine: "04/20/2021",
                Team: "Apple",
                finish: false,
            },
        ],
        lateEmployee: [{
                team: "Frozen Yogurt",
                name: "John",
                contact: "@gmail.com",
                in: new Date(1618562483000),
                out: new Date(),
            },
            {
                team: "Gingerbread",
                name: "Mary",
                contact: "@gmail.com",
                in: 9.0,
                out: 16.55,
            },
            {
                team: "Frozen Yogurt",
                name: "Sea",
                contact: "@gmail.com",
                in: 9.0,
                out: 18.09,
            },
            {
                team: "Gingerbread",
                name: "Pete",
                contact: "@gmail.com",
                in: 9.0,
                out: 17.59,
            },
            {
                team: "Gingerbread",
                name: "Evan",
                contact: "@gmail.com",
                in: 9.0,
                out: 20,
            },
            {
                team: "Frozen Yogurt",
                name: "Isac",
                contact: "@gmail.com",
                in: 9.0,
                out: 18,
            },
            {
                team: "Frozen Yogurt",
                name: "Jess",
                contact: "@gmail.com",
                in: 9.0,
                out: 16,
            },
            {
                team: "KitKat",
                name: "Oven",
                contact: "@gmail.com",
                in: 9.0,
                out: 17,
            },
            {
                team: "Donut",
                name: "Tibb",
                contact: "@gmail.com",
                in: 9.0,
                out: 17,
            },
            {
                team: "KitKat",
                name: "Pop",
                contact: "@gmail.com",
                in: 9.0,
                out: 17,
            },
            {
                team: "Frozen Yogurt",
                name: "Isac",
                contact: "@gmail.com",
                in: 9.0,
                out: 17,
            },
            {
                team: "Frozen Yogurt",
                name: "Jess",
                contact: "@gmail.com",
                in: 9.0,
                out: 17,
            },
            {
                team: "KitKat",
                name: "Oven",
                contact: "@gmail.com",
                in: 9.0,
                out: 17,
            },
            {
                team: "Donut",
                name: "Tibb",
                contact: "@gmail.com",
                in: 9.0,
                out: 17,
            },
            {
                team: "KitKat",
                name: "Pop",
                contact: "@gmail.com",
                in: 9.0,
                out: 17,
            },
        ],
        OTEmployee: [{
                team: "Frozen Yogurt",
                name: "John",
                contact: "@gmail.com",
                time: 10,
            },
            {
                team: "Gingerbread",
                name: "Mary",
                contact: "@gmail.com",
                time: 0,
            },

            {
                team: "Frozen Yogurt",
                name: "John",
                contact: "@gmail.com",
                time: 15,
            },
            {
                team: "Gingerbread",
                name: "Mary",
                contact: "@gmail.com",
                time: 3,
            },
            {
                team: "Frozen Yogurt",
                name: "Sea",
                contact: "@gmail.com",
                time: 5,
            },
            {
                team: "Gingerbread",
                name: "Pete",
                contact: "@gmail.com",
                time: 6,
            },
            {
                team: "Gingerbread",
                name: "Evan",
                contact: "@gmail.com",
                time: 8,
            },
            {
                team: "Frozen Yogurt",
                name: "Isac",
                contact: "@gmail.com",
                time: 1,
            },
            {
                team: "Frozen Yogurt",
                name: "Jess",
                contact: "@gmail.com",
                time: 9,
            },
            {
                team: "KitKat",
                name: "Oven",
                contact: "@gmail.com",
                time: 20,
            },
            {
                team: "Donut",
                name: "Tibb",
                contact: "@gmail.com",
                time: 10,
            },
            {
                team: "KitKat",
                name: "Pop",
                contact: "@gmail.com",
                time: 19,
            },
        ],
        items: [],
    },
    getters: {
        items: state => {
            return state.items;
        }
    },
    mutations: {
        SET_Item(state, items) {
            state.items = items
        }
    },
    actions: {
        loadItems({ commit }) {
            axios
                .get('Your API link')
                .then((response)

                )
        }
    },
    modules: {},
});