export default {
    teams: [{
            id: 1,
            name: "Frozen Yogurt",
            members: [{
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                {
                    id: 1,
                    name: "Noah	Emma",
                    salary: 23700,
                    status: "worker",
                    period: 13,
                    contact: "gmail.com",
                    pic: "https://cdn.psychologytoday.com/sites/default/files/styles/article-inline-half-caption/public/field_blog_entry_images/2018-09/shutterstock_648907024.jpg?itok=0hb44OrI",
                },
                {
                    id: 2,
                    name: "Oliver	Ava",
                    salary: 26200,
                    status: "worker",
                    period: 2,
                    contact: "gmail.com",
                    pic: "https://qodebrisbane.com/wp-content/uploads/2019/07/This-is-not-a-person-2-1.jpeg",
                },
                {
                    id: 3,
                    name: "William	Sophia",
                    salary: 30500,
                    status: "worker",
                    period: 1,
                    contact: "gmail.com",
                    pic: "https://play-images-prod-cms.tech.tvnz.co.nz/api/v1/web/image/content/dam/images/entertainment/shows/p/person-of-interest/personofinterest_coverimg.png.2017-03-08T11:21:33+13:00.jpg?width=960&height=540",
                },
                {
                    id: 4,
                    name: "Elijah	Isabella",
                    salary: 35600,
                    status: "worker",
                    period: 5,
                    contact: "gmail.com",
                    pic: "https://cdn.now.howstuffworks.com/media-content/0b7f4e9b-f59c-4024-9f06-b3dc12850ab7-1920-1080.jpg",
                },
                {
                    id: 5,
                    name: "James	Charlotte",
                    salary: 37500,
                    status: "worker",
                    period: 3,
                    contact: "gmail.com",
                    pic: "https://thumbor.forbes.com/thumbor/fit-in/1200x0/filters:format(jpg)/https://specials-images.forbesimg.com/imageserve/5f469ea85cc82fc8d6083f05/0x0.jpg",
                },
                {
                    id: 6,
                    name: "Benjamin	Amelia",
                    salary: 39200,
                    status: "worker",
                    period: 1,
                    contact: "gmail.com",
                    pic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNsO8UKeJSffZI-UxtGBNbV_VHSel-RHHtog&usqp=CAU",
                },
                {
                    id: 7,
                    name: "Lucas	Mia",
                    salary: 40800,
                    status: "intern student",
                    period: 1,
                    contact: "gmail.com",
                    pic: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8cGVyc29ufGVufDB8fDB8&ixlib=rb-1.2.1&w=1000&q=80",
                },
                {
                    id: 8,
                    name: "Mason	Harper",
                    salary: 45200,
                    status: "intern student",
                    period: 1,
                    contact: "gmail.com",
                    pic: "http://www.scottcochrane.com/wp-content/uploads/2018/05/One-Person-2.jpg",
                },
                {
                    id: 9,
                    name: "Ethan	Evelyn",
                    salary: 51800,
                    status: "intern student",
                    period: 1,
                    contact: "gmail.com",
                    pic: "https://www.guinnessworldrecords.com/Images/Greta-Thunberg-youngest-time-person-of-the-yearthumbnail_tcm25-603423.jpg",
                },
            ],
            progress: 20,
            img: "https://storage.googleapis.com/gen-atmedia/3/2015/08/2bb3585735eedc2040f79a4609514e0e4af2ab3d.jpeg",
        },
        {
            id: 2,
            name: "Ice cream sandwich",
            members: [{
                    id: 0,
                    name: "Liam	Olivia",
                    salary: 15900,
                    status: "worker",
                    period: 1,
                    contact: "sarasgmail.com",
                    pic: "https://mindbodygreen-res.cloudinary.com/images/w_767,q_auto:eco,f_auto,fl_lossy/usr/RetocQT/sarah-fielding.jpg",
                },
                {
                    id: 1,
                    name: "Noah	Emma",
                    salary: 23700,
                    status: "worker",
                    period: 13,
                    contact: "gmail.com",
                    pic: "https://cdn.psychologytoday.com/sites/default/files/styles/article-inline-half-caption/public/field_blog_entry_images/2018-09/shutterstock_648907024.jpg?itok=0hb44OrI",
                },
                {
                    id: 2,
                    name: "Oliver	Ava",
                    salary: 26200,
                    status: "worker",
                    period: 2,
                    contact: "gmail.com",
                    pic: "https://qodebrisbane.com/wp-content/uploads/2019/07/This-is-not-a-person-2-1.jpeg",
                },
            ],
            progress: 90,
            img: "https://hips.hearstapps.com/vidthumb/images/delish-giant-ice-cream-sandwich-cake-still002-1529699322.jpg?crop=0.716xw%3A0.718xh%3B0.151xw%2C0.134xh&resize=480%3A270",
        },
        {
            id: 3,
            name: "Eclair",
            members: [],
            progress: 30,
            img: "http://www.ndtv.com/cooks/images/chocolate.eclairs.jpg",
        },
        {
            id: 4,
            name: "Cupcake",
            members: [],
            progress: 100,
            img: "https://hips.hearstapps.com/del.h-cdn.co/assets/18/07/1518475314-vanilla-cupcake-horizontal-.jpg",
        },
        {
            id: 5,
            name: "Gingerbread",
            members: [],
            progress: 81,
            img: "https://www.superhealthykids.com/wp-content/uploads/2020/11/Gingerbread-Cookies-4sml.jpg",
        },
        {
            id: 6,
            name: "Jelly bean",
            members: [],
            progress: 40,
            img: "https://www.atrafloor.com/app/uploads/2017/01/jelly-bean-vinyl-flooring-multicolour.jpg",
        },
        {
            id: 7,
            name: "Lollipop",
            members: [],
            progress: 99,
            img: "http://sc01.alicdn.com/kf/H012b3ea0f9f74449b3f33e3b6ba7a2e77.jpg",
        },
        {
            id: 8,
            name: "Honeycomb",
            members: [],
            progress: 12,
            img: "https://www.grandturkishbazaar.com/wp-content/uploads/2019/01/turkish-honeycomb.jpg",
        },
        {
            id: 9,
            name: "Donut",
            members: [],
            progress: 60,
            img: "https://www.starbucks.co.th/stb-media/2020/08/7.Glaze-Donut1080-1.png",
        },
        {
            id: 10,
            name: "KitKat",
            members: [],
            progress: 50,
            img: "https://i.insider.com/5b5856a9c171cb21008b4639?width=1136&format=jpeg",
        },
    ],
}